name: pyomo_ketchup
channels:
  - conda-forge
  - defaults
  - pip
dependencies:
  - python=3.12.9
  - openpyxl=3.1.5
  - pandas=2.3.3
  - ipopt=3.14.19 
  - pyomo=6.9.4
  - scipy=1.16.2
  - pyyaml=6.0.3
  - pip
  - pip:
    - cobra==0.29.1
    - streamlit==1.50.0
